name: tutor_ai
description: TutorAI - your personal AI tutor.
publish_to: "none"
version: 0.2.0+2

environment:
  sdk: ">=3.4.0 <4.0.0"
  flutter: ">=3.22.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  image_picker: ^1.1.2
  google_mlkit_text_recognition: ^0.17.1
  image: ^4.10.1
  google_mlkit_document_scanner: ^0.6.1
  file_picker: ^13.1.0
  flutter_pdf_text: ^0.9.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/tutor_ai_hero.png
    - assets/tutorai_icons/